### ISSUE TITLE
pyter  pip install error

### ISSUE THREAD

**Issue by hittle2015** [gcunhase/NLPMetrics#1]
I get the following error while pip install:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_xf5pznq/distribute/

**Comment by gcunhase** [comment]
You probably have an out of date version of `pip` and /or `setuptools`.

Can you try running `sudo pip install --upgrade pip setuptools`?

**Comment by gcunhase** [comment]
Due to lack of activity and because I think my answer will solve this problem, I'm closing this issue. I have no problem reopening it later if the need arises.
